### ISSUE TITLE
Not working on IEEExplore

### ISSUE THREAD

**Issue by geledek** [lushl9301/Non-Click-NUS-Library-Proxy#3]
ACM library is working. 
IEEExplore still requires manual login.
E.g. http://ieeexplore.ieee.org/abstract/document/7557429/

**Comment by geledek** [comment]
Sometimes it works.

**Comment by koallen** [comment]
The script only works on `http://ieeexplore.ieee.org/document/*`, so `http://ieeexplore.ieee.org/abstract/document/7557429/` does not work.

@lushl9301 we should match `http://ieeexplore.ieee.org/*` instead.

**Comment by koallen** [comment]
@geledek fixed by the latest commit. Closing.

Please update your script from Tampermonkey.

**Comment by lushl9301** [comment]
@geledek told you :+1:

**Comment by geledek** [comment]
http://ieeexplore.ieee.org/abstract/document/4812447/ still not working.

**Comment by koallen** [comment]
You need to update your script, if you use Chrome, click on the Tempermonkey icon and select "Check for userscript updates", then try again with the link.

I already tested your link and it's working in the latest version.
